name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate Flutter Project Structure
        run: |
          mkdir temp_project
          cd temp_project
          flutter create --org com.supra.ecu --project-name supra_ecu_dashboard .
          rm -rf lib/main.dart pubspec.yaml
          cd ..
          cp -r temp_project/* .
          rm -rf temp_project

      # LANGKAH INJEKSI OTOMATIS: Memaksa Android mengizinkan koneksi WebSocket non-secure (ws://)
      - name: Inject Cleartext Traffic Permission
        run: |
          MANIFEST_PATH="android/app/src/main/AndroidManifest.xml"
          if [ -f "$MANIFEST_PATH" ]; then
            sed -i 's/<application/<application android:usesCleartextTraffic="true"/g' "$MANIFEST_PATH"
            echo "Sukses menyuntikkan izin keamanan jaringan WebSocket!"
          else
            echo "Error: AndroidManifest.xml tidak ditemukan!"
            exit 1
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --no-shrink

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dashboard-ECU-SupraX
          path: build/app/outputs/flutter-apk/app-release.apk
